#!/bin/bash

ssh eechris@cpjobling.org.uk 'cd public_html/at-m42; svn update'
#svn export . ./at-m42-source
#zip ./at-m42-source
#rm -rf ./at-m42-source
#scp at-m42-source.zip eechris@cpjobling.org.uk:public_html/at-m42


